- name: Sashay
  description: Sashay
  github: 'https://bitbucket.org/seanerussell/sashay'
  v1: true
  language: '?'
  category: '?'
- name: swaggydoc
  description: swaggydoc
  github: 'http://grails.org/plugin/swaggydoc'
  v1: true
  language: '?'
  category: '?'
- name: Hapi
  description: >-
    A Hapi plugin that automatically creates Swagger documentation AND validates
    request/response parameters using the JSON Schema spec.
  github: 'http://hapijs.com/'
  v1: true
  language: '?'
  category: '?'
- name: Swaggervel
  description: Swaggervel
  github: 'https://packagist.org/packages/jlapp/swaggervel'
  v1: true
  language: '?'
  category: '?'
- name: Scalatra
  description: Scalatra
  github: 'http://www.scalatra.org/'
  v1: true
  language: '?'
  category: '?'
- name: Swagger Guide
  description: see the Swagger Guide
  github: 'http://www.scalatra.org/2.2/guides/swagger.html'
  v1: true
  language: '?'
  category: '?'
- name: playframework
  description: >-
    Creates swagger docs from easily readable ascii text placed in the code.
    Depends on playframework, but may also be used in other frameworks.
  github: 'http://www.playframework.com/'
  v1: true
  language: '?'
  category: '?'
- name: Postman
  description: Creates a Postman collection from live Swagger documentation
  github: 'http://www.getpostman.com/'
  v1: true
  language: '?'
  category: '?'
- name: swagger-docs-cfml
  description: swagger-docs-cfml
  github: 'https://github.com/webonix/swagger-docs-cfml'
  v1: true
  language: ColdFusion
  category: '?'
  archived: false
  stars: 3
  watch: 2
  updated: '2014-10-27T08:20:51Z'
  issues: 0
- name: Swagger Framework
  description: Swagger Framework
  github: 'https://github.com/silas/swagger-framework'
  v1: true
  language: JavaScript
  category: '?'
  archived: true
  stars: 54
  watch: 2
  updated: '2018-09-02T07:20:38Z'
  issues: 2
- name: swagger_engine
  description: swagger_engine
  github: 'https://github.com/batdevis/swagger_engine'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 44
  watch: 6
  updated: '2018-08-13T00:16:20Z'
  issues: 11
- name: swagger-angular-client
  description: >-
    Client library generator which can be used to create framework or 

    platform-specific Swagger clients given a transport method (e.g.
    swagger-angular-client or swagger-node-client).
  github: 'https://github.com/signalfx/swagger-angular-client'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 81
  watch: 66
  updated: '2018-11-07T00:47:45Z'
  issues: 3
- name: swagger-docs
  description: swagger-docs
  github: 'https://github.com/richhollis/swagger-docs'
  v1: true
  language: Ruby
  category: '?'
  archived: false
  stars: 670
  watch: 13
  updated: '2018-11-22T08:48:32Z'
  issues: 35
- name: swagger
  description: swagger
  github: 'https://github.com/EiffelWebFramework/swagger'
  v1: true
  language: Eiffel
  category: '?'
  archived: false
  stars: 5
  watch: 4
  updated: '2015-11-05T02:15:08Z'
  issues: 0
- name: swaggerj4
  description: swaggerj4
  github: 'https://github.com/SmartBear/swagger4j'
  v1: true
  language: Java
  category: '?'
  archived: false
  stars: 23
  watch: 37
  updated: '2018-10-05T06:45:31Z'
  issues: 8
- name: swaggerapi
  description: swaggerapi
  github: 'https://github.com/ROAMSYS/swaggerapi'
  v1: true
  language: Java
  category: '?'
  archived: false
  stars: 12
  watch: 10
  updated: '2018-04-25T12:01:46Z'
  issues: 0
- name: swagger-jaxrs-doclet
  description: swagger-jaxrs-doclet
  github: 'https://github.com/ryankennedy/swagger-jaxrs-doclet'
  v1: true
  language: Java
  category: '?'
  archived: true
  stars: 90
  watch: 21
  updated: '2018-04-24T12:01:39Z'
  issues: 33
- name: swagger-node-client
  description: swagger-node-client
  github: 'https://github.com/signalfx/swagger-node-client'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 10
  watch: 61
  updated: '2018-06-23T06:37:12Z'
  issues: 2
- name: springfox
  description: springfox
  github: 'https://github.com/springfox/springfox-grails-integration'
  v1: true
  language: Groovy
  category: '?'
  archived: false
  stars: 10
  watch: 6
  updated: '2018-11-09T12:45:40Z'
  issues: 12
- name: flask-restful-swagger
  description: flask-restful-swagger
  github: 'https://github.com/rantav/flask-restful-swagger'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 518
  watch: 26
  updated: '2018-11-22T10:48:26Z'
  issues: 44
- name: go-restful
  description: go-restful
  github: 'https://github.com/emicklei/go-restful'
  v1: true
  language: Go
  category: '?'
  archived: false
  stars: 2985
  watch: 155
  updated: '2018-11-23T06:50:01Z'
  issues: 11
- name: Here is a demo application
  description: >-
    SpringFox Grails integration library that produces swagger specification
    documentation for Grails 3.x. Here is a demo application showcasing the
    library integration.
  github: 'https://github.com/springfox/springfox-grails-demo'
  v1: true
  language: Groovy
  category: '?'
  archived: false
  stars: 5
  watch: 2
  updated: '2018-05-31T05:48:37Z'
  issues: 1
- name: swagger-assert
  description: swagger-assert
  github: 'https://github.com/gong023/swagger-assert'
  v1: true
  language: PHP
  category: '?'
  archived: false
  stars: 13
  watch: 3
  updated: '2018-05-07T17:43:57Z'
  issues: 1
- name: swagger-jack
  description: swagger-jack
  github: 'https://github.com/worldline/swagger-jack'
  v1: true
  language: CoffeeScript
  category: '?'
  archived: false
  stars: 46
  watch: 12
  updated: '2018-08-22T09:50:29Z'
  issues: 11
- name: Restler
  description: Restler
  github: 'https://github.com/Luracast/Restler'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 1261
  watch: 113
  updated: '2018-11-15T13:43:41Z'
  issues: 43
- name: swagger-cli-client
  description: swagger-cli-client
  github: 'https://github.com/signalfx/swagger-cli-client'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 32
  watch: 62
  updated: '2018-10-10T11:51:04Z'
  issues: 2
- name: django-tastypie-swagger
  description: django-tastypie-swagger
  github: 'https://github.com/concentricsky/django-tastypie-swagger'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 136
  watch: 18
  updated: '2018-10-27T18:18:52Z'
  issues: 47
- name: swagger-express
  description: swagger-express
  github: 'https://github.com/fliptoo/swagger-express'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 217
  watch: 11
  updated: '2018-11-14T18:47:36Z'
  issues: 14
- name: fubumvc-swagger
  description: fubumvc-swagger
  github: 'https://github.com/KevM/fubumvc-swagger'
  v1: true
  language: 'C#'
  category: '?'
  archived: false
  stars: 12
  watch: 3
  updated: '2018-02-09T18:56:54Z'
  issues: 2
- name: Swagger integration
  description: >-
    a high-performance .NET web services platform that simplifies the 

    development of high-performance REST (JSON, XML, JSV, HTML, MsgPack, 

    ProtoBuf, CSV) and WCF SOAP Web Services. Has support for Swagger
    integration.
  github: 'https://github.com/ServiceStack/ServiceStack/wiki/Swagger-API'
  v1: true
  language: 'C#'
  category: '?'
  archived: false
  stars: 4372
  watch: 570
  updated: '2018-11-22T22:55:34Z'
  issues: 35
- name: '[Source]'
  description: 'Swagger Documentation for Grails Controllers. [Source]'
  github: 'https://github.com/rahulsom/swaggydoc'
  v1: true
  language: Groovy
  category: '?'
  archived: true
  stars: 29
  watch: 6
  updated: '2018-08-28T07:22:00Z'
  issues: 27
- name: hapi-swagger
  description: hapi-swagger
  github: 'https://github.com/glennjones/hapi-swagger'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 662
  watch: 30
  updated: '2018-11-21T13:56:38Z'
  issues: 108
- name: gform-admin
  description: gform-admin
  github: 'https://github.com/stemey/gform-admin'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 34
  watch: 3
  updated: '2018-02-09T18:55:49Z'
  issues: 0
- name: ratify
  description: ratify
  github: 'https://github.com/mac-/ratify'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 72
  watch: 3
  updated: '2018-06-09T09:05:39Z'
  issues: 11
- name: django-rest-swagger
  description: django-rest-swagger
  github: 'https://github.com/marcgibbons/django-rest-swagger'
  v1: true
  language: Python
  category: '?'
  archived: false
  stars: 2098
  watch: 72
  updated: '2018-11-22T20:32:24Z'
  issues: 136
- name: swagger-client-generator
  description: swagger-client-generator
  github: 'https://github.com/signalfx/swagger-client-generator'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 35
  watch: 63
  updated: '2018-08-21T23:18:03Z'
  issues: 4
- name: source2swagger
  description: source2swagger
  github: 'https://github.com/solso/source2swagger'
  v1: true
  language: Ruby
  category: '?'
  archived: false
  stars: 67
  watch: 6
  updated: '2018-02-09T18:56:43Z'
  issues: 3
- name: octohipster
  description: octohipster
  github: 'https://github.com/myfreeweb/octohipster'
  v1: true
  language: Clojure
  category: '?'
  archived: false
  stars: 79
  watch: 9
  updated: '2017-10-03T10:19:40Z'
  issues: 0
- name: spray-swagger
  description: spray-swagger
  github: 'https://github.com/gettyimages/spray-swagger'
  v1: true
  language: Scala
  category: '?'
  archived: false
  stars: 149
  watch: 42
  updated: '2018-07-24T19:22:25Z'
  issues: 23
- name: swagger-angular-client
  description: swagger-angular-client
  github: 'https://github.com/signalfx/swagger-angular-client'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 81
  watch: 66
  updated: '2018-11-07T00:47:45Z'
  issues: 3
- name: dotswaggen
  description: dotswaggen
  github: 'https://github.com/skrusty/dotswaggen'
  v1: true
  language: 'C#'
  category: '?'
  archived: false
  stars: 13
  watch: 3
  updated: '2017-06-18T07:01:32Z'
  issues: 0
- name: Swagger spec generator
  description: Swagger spec generator
  github: 'https://github.com/yvasiyarov/swagger'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 738
  watch: 32
  updated: '2018-11-23T06:19:05Z'
  issues: 36
- name: tornado-swagger
  description: tornado-swagger
  github: 'https://github.com/SerenaFeng/tornado-swagger'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 24
  watch: 1
  updated: '2018-11-16T14:44:39Z'
  issues: 4
- name: restapidoc
  description: restapidoc
  github: 'https://github.com/siemens/restapidoc'
  v1: true
  language: Groovy
  category: '?'
  archived: false
  stars: 28
  watch: 10
  updated: '2018-01-30T15:58:50Z'
  issues: 3
- name: Swagger2Postman
  description: Swagger2Postman
  github: 'https://github.com/josephpconley/swagger2postman'
  v1: true
  language: Scala
  category: '?'
  archived: false
  stars: 70
  watch: 4
  updated: '2018-08-30T14:52:00Z'
  issues: 3
- name: Swagger Validation
  description: Swagger Validation
  github: 'https://github.com/wonderlic/swagger-validation'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 8
  watch: 1
  updated: '2018-02-17T23:53:18Z'
  issues: 2
- name: swagger-validate
  description: swagger-validate
  github: 'https://github.com/signalfx/swagger-validate'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 20
  watch: 62
  updated: '2018-03-12T06:42:23Z'
  issues: 4
- name: FubuMVC
  description: >-
    This project helps your FubuMVC web application generate API documentation
    via Swagger.
  github: 'https://github.com/DarthFubuMVC/fubumvc'
  v1: true
  language: 'C#'
  category: '?'
  archived: false
  stars: 428
  watch: 31
  updated: '2018-10-27T15:45:49Z'
  issues: 89
- name: swagger-validator
  description: swagger-validator
  github: 'https://github.com/kenshoo/swagger-validator'
  v1: true
  language: Java
  category: '?'
  archived: false
  stars: 10
  watch: 165
  updated: '2017-07-03T05:55:08Z'
  issues: 2
- name: NelmioApiDocBundle
  description: NelmioApiDocBundle
  github: 'https://github.com/nelmio/NelmioApiDocBundle'
  v1: true
  language: PHP
  category: '?'
  archived: false
  stars: 1569
  watch: 73
  updated: '2018-11-22T16:05:18Z'
  issues: 55
- name: beego
  description: beego
  github: 'https://github.com/astaxie/beego'
  v1: true
  language: Go
  category: '?'
  archived: false
  stars: 17871
  watch: 1201
  updated: '2018-11-23T09:50:11Z'
  issues: 531
- name: swagger-ajax-client
  description: swagger-ajax-client
  github: 'https://github.com/signalfx/swagger-ajax-client'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 15
  watch: 62
  updated: '2018-04-18T17:21:06Z'
  issues: 0
- name: Swagger-ui
  description: include Swagger-ui as mountable rails engine.
  github: 'https://github.com/swagger-api/swagger-ui'
  v1: true
  language: JavaScript
  category: '?'
  archived: false
  stars: 13351
  watch: 643
  updated: '2018-11-23T10:04:23Z'
  issues: 291
- name: swagger4spring-web
  description: swagger4spring-web
  github: 'https://github.com/wkennedy/swagger4spring-web'
  v1: true
  language: Java
  category: '?'
  archived: false
  stars: 91
  watch: 19
  updated: '2018-10-28T05:21:40Z'
  issues: 38
- name: ServiceStack
  description: ServiceStack
  github: 'https://github.com/ServiceStack/ServiceStack'
  v1: true
  language: 'C#'
  category: '?'
  archived: false
  stars: 4372
  watch: 570
  updated: '2018-11-22T22:55:34Z'
  issues: 35
- name: Api-doc
  description: Api-doc
  github: 'https://github.com/sun-opsys/api-doc'
  v1: true
  language: Scala
  category: '?'
  archived: false
  stars: 37
  watch: 27
  updated: '2018-07-23T05:56:27Z'
  issues: 9
